### ISSUE TITLE
Flask Ask doesn't parse time stamp from Alexa properly...

### ISSUE THREAD

**Issue by robputt796** [johnwheeler/flask-ask#152]
Traceback (most recent call last):
  File "/opt/HomeApp/lib/python3.4/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/HomeApp/lib/python3.4/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/HomeApp/lib/python3.4/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/HomeApp/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/HomeApp/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/HomeApp/lib/python3.4/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/HomeApp/lib/python3.4/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/HomeApp/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/opt/HomeApp/lib/python3.4/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/HomeApp/lib/python3.4/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/HomeApp/lib/python3.4/site-packages/flask_ask/core.py", line 571, in _flask_view_func
    ask_payload = self._alexa_request(verify=self.ask_verify_requests)
  File "/opt/HomeApp/lib/python3.4/site-packages/flask_ask/core.py", line 533, in _alexa_request
    timestamp = aniso8601.parse_datetime(alexa_request_payload['request']['timestamp'])
  File "/opt/HomeApp/lib/python3.4/site-packages/aniso8601/time.py", line 120, in parse_datetime
    isodatestr, isotimestr = isodatetimestr.split(delimiter)
AttributeError: 'int' object has no attribute 'split'

**Comment by robputt796** [comment]
Here is a raw example of the request from Alexa...

{
  "session": {
    "sessionId": "SessionId.",
    "application": {
      "applicationId": "amzn1.ask.skill."
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account."
    },
    "new": true
  },
  "request": {
    "type": "LaunchRequest",
    "requestId": "EdwRequestId.ff5385a8-ad2b-435e-a2e7-807aa422875d",
    "locale": "en-GB",
    "timestamp": "2017-07-08T07:38:00Z"
  },
  "version": "1.0"
}

**Comment by robputt796** [comment]
After adding some debug logs to the application I found alexa_request_payload['request']['timestamp'] is indeed an integer...

1499500133708

**Comment by robputt796** [comment]
ok, I monkey patched this with a try except, basically if the conversion fails and the thing is already an integer it assumes its already a timestamp, not sure if this is the right way of dealing with this case but it appears to work for now.

**Comment by jamessun** [comment]
[Possible related issue?](https://forums.developer.amazon.com/questions/78372/timestamp-is-sent-in-different-formats.html)

**Comment by robputt796** [comment]
Yep looks like the same symptoms to me... reluctant to raise a PR simply because it should probably be fixed upstream by Amazon.

**Comment by voutilad** [comment]
@robputt796 do you see this behavior when deploying the app and using an Alexa enabled device? Or are you only using Amazon's testing interface on their skill config page?

Amazon's testing interface is beyond horrible and routinely doesn't follow their own specifications. (See all the issues we've had regarding it not providing a Context in the request...which is required per Amazon's API documentation.)

**Comment by robputt796** [comment]
I've been testing against echosim.io. The skill is not published, its a private skill which I use for my custom home automation system, so it basically runs in test mode all the time. I probably need to put those print lines back in there and see if it receives an integer with echosim or if it gets a proper ISO formatted datetime.

**Comment by voutilad** [comment]
Definitely turn up debugging if you can and see if you can capture the JSON request coming into the skill. My guess is the request is actually invalid. (I'm starting to think it might make sense to add some spec definition to check against and raise errors if the request appears invalid.)

For reference, [per Amazon](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service#timestamp):

> The timestamp is provided as an ISO 8601 formatted string (for example, 2015-05-13T12:34:56Z). Your code needs to parse the string into a date object, then verify that it is within the tolerance your web service allows (no more than 150 seconds)

A tool like Echosim or even Amazon's own tools might not actually conform to Amazon's specs and most people won't notice since Amazon forces responsibility on the app developer to validate a lot of the pieces. We could turn a blind eye to some of these bad inputs, but from my experience with Amazon, if they trip your app during testing during a skill submission then your skill will get rejected.

This has happened before with `Context` elements being left out of requests. Amazon doesn't even generate them with their testing tool, either! Yet, per their own docs, it should be part of every request. It's almost like they want this to be difficult.

**Comment by i-ghost** [comment]
Looks like a case of Amazon's testing tools using a different timestamp format than what the device sends.

Testing using their developer.amazon.com:

```python
_ = alexa_request_payload['request']['timestamp']
print(_)
1499561132768
type(_)
<class 'int'>
```

Testing using a real Echo Dot:

```python
_ = alexa_request_payload['request']['timestamp']
print(_)
'2017-07-09T00:45:19Z'
type(_)
<class 'str'>
```

**Comment by LiteWait** [comment]
Does anyone have a fix for this?  I don't have a device.

**Comment by m19brandon** [comment]
@LiteWait Under the text tab, run your text test which will fail. Then copy the Service Request JSON object. Switch to the JSON tab and paste into the JSON Request field. That is working for me.

**Comment by LiteWait** [comment]
Thanks.

My workaround was to patch core.py:

try:
                timestamp =
aniso8601.parse_datetime(alexa_request_payload['request']['timestamp'])
            except AttributeError:
                import datetime
                timestamp = datetime.datetime.now()  # slam in a timestamp!

**Comment by LiteWait** [comment]
Maybe a better fix is:

try:
                timestamp = aniso8601.parse_datetime(alexa_request_payload['request']['timestamp'])
            except AttributeError:
                import datetime
                timestamp = datetime.datetime.fromtimestamp(alexa_request_payload['request']['timestamp']/1000)

**Comment by lheston** [comment]
I tried that work around and it solved my other issues. But I still cannot seem to pass any sort of date to alexa correctly using the AMAZON.DATE slot type.

**Comment by voutilad** [comment]
Since this seems to impact a lot of folks, I'll work on fixing the logic to support the proper ISO8601 date string and an integer value representing an epoch timestamp. I want to preserve the timestamp validation capability in the process.

**Comment by pzzd** [comment]
I also opened a ticket with Amazon to look into fixing the Text testing tool in the skill admin site at developer.amazon.com.

**Comment by santosh719** [comment]
Temporary fix , add this - 

app.config['ASK_VERIFY_REQUESTS'] = False

Just to get the skill working. As long as you don't need this. 
Worked for me!

**Comment by voutilad** [comment]
I've added a change in a branch that looks to sanely handle these two types of timestamps. It raises some different questions about the logic for getting things like timestamp and app id if verification is disabled, but for now let's see if this resolves your issues. 

I added some test cases to try to simulate the problem, but need your help testing it.

**Can someone experiencing the issue try installing the version from the branch?** I don't have time the next couple days to try a live Alexa test. 

To install the branch using pip, from your virtual environment or wherever you've been using Flask-Ask:
```bash
pip install -U git+https://github.com/johnwheeler/flask-ask@issue-152
```

If you're doing anything from source, just clone the branch `issue-152`.

**Comment by MrLemur** [comment]
I've confirmed that by upgrading to the issue-152 branch, I can now get a successful response using the text and JSON request testing in the Alexa dev dashboard.

**Comment by voutilad** [comment]
I've cut a new release containing the timestamp changes: [v0.9.5](https://pypi.python.org/pypi/Flask-Ask/0.9.5)

Github auto-closed this issue because I said the magic words "fix #152" in my commit message, so please re-open if there are issues after upgrading.

**Comment by pzzd** [comment]
I'm getting "ValueError: year is out of range" now with v0.9.5, using the Text tool in developer.amazon.com. It's working fine with the JSON tool.

Traceback (most recent call last):
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask_ask/core.py", line 591, in _flask_view_func
    ask_payload = self._alexa_request(verify=self.ask_verify_requests)
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask_ask/core.py", line 536, in _alexa_request
    timestamp = self._parse_timestamp(raw_timestamp)
  File "/Users/p/projects/alexa/uac-2017-alexa-engage/venv/lib/python2.7/site-packages/flask_ask/core.py", line 562, in _parse_timestamp
    return datetime.utcfromtimestamp(timestamp)
ValueError: year is out of range

**Comment by LiteWait** [comment]
I think the fix to that is:
return datetime.utcfromtimestamp(timestamp/1000)

**Comment by voutilad** [comment]
@pzzd can you provide any more details such as the timestamp value you're sending in the request? That error is very strange as the `datetime.utcfromtimestamp()` method is able to handle the max integer value and even handle negative inputs.

Which OS and Python version are you using? Some of the time handling in Python is system dependent.

**Comment by pzzd** [comment]
I used the Text tool from Alexa skills admin page at developer.amazon.com. That tool produced this request:

`{
  "session": {
    "sessionId": "SessionId.8474c070-b12c-46b5-be46-241d1aa51dfa",
    "application": {
      "applicationId": "amzn1.ask.skill.23926711-b8dd-47ad-a95d-ef1d693d19eb"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AH5QJGCCGTLR6JOF2SFBR6PAPCPWJL52UPSDTS4L7I3WI3537DLJPBBUYSHJCCPGY5YJARNEZZ7CDY4DTK234LMMO5L5KTE3DPPGSLSJS5DYNVDYMAUM3SYZGCK5IGOJSWRILK4T2DTU7PMTPETYTMFKWMOBG22LPVNZA2CYXU5WVQ3KVUQZ2C6NCD3XDJFVBBGMQBD7Z2NXSKI"
    },
    "new": true
  },
  "request": {
    "type": "LaunchRequest",
    "requestId": "EdwRequestId.45ff9fa9-d4cd-45d8-9d28-81ae39cbee9a",
    "locale": "en-US",
    "timestamp": "2017-07-11T14:21:47Z"
  },
  "version": "1.0"
}`

However, this request works from the JSON tool.

**Comment by voutilad** [comment]
Maybe you can try the following and verify it works on your system? You'll need to clone the master branch and then `pip install Flask-Ask`. The following works locally on my macOS 10.12.5 system:

**Confirming version:**
``` bash
$ python -V && which python
Python 2.7.10
/Users/dave/.virtualenvs/flask-py2-10/bin/python
```

**Running helloworld sample:**
``` bash
$ ASK_VERIFY_REQUESTS=false python samples/helloworld/helloworld.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 189-811-296
```

**Create a file called `json` containing your sample (this step is just showing my copy):**
``` bash
$ cat json
{ "session": { "sessionId": "SessionId.8474c070-b12c-46b5-be46-241d1aa51dfa", "application": { "applicationId": "amzn1.ask.skill.23926711-b8dd-47ad-a95d-ef1d693d19eb" }, "attributes": {}, "user": { "userId": "amzn1.ask.account.AH5QJGCCGTLR6JOF2SFBR6PAPCPWJL52UPSDTS4L7I3WI3537DLJPBBUYSHJCCPGY5YJARNEZZ7CDY4DTK234LMMO5L5KTE3DPPGSLSJS5DYNVDYMAUM3SYZGCK5IGOJSWRILK4T2DTU7PMTPETYTMFKWMOBG22LPVNZA2CYXU5WVQ3KVUQZ2C6NCD3XDJFVBBGMQBD7Z2NXSKI" }, "new": true }, "request": { "type": "LaunchRequest", "requestId": "EdwRequestId.45ff9fa9-d4cd-45d8-9d28-81ae39cbee9a", "locale": "en-US", "timestamp": "2017-07-11T14:21:47Z" }, "version": "1.0" }

```

**From another terminal, POST'ing your sample JSON:**
``` bash
$ curl -v -H "Content-Type: application/json" --no-keepalive --data @json http://127.0.0.1:5000/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> POST / HTTP/1.1
> Host: 127.0.0.1:5000
> User-Agent: curl/7.51.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 634
>
* upload completely sent off: 634 out of 634 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 416
< Server: Werkzeug/0.12.2 Python/2.7.10
< Date: Tue, 11 Jul 2017 15:08:08 GMT
<
* Curl_http_done: called premature == 0
* Closing connection 0
{"response": {"card": {"content": "Welcome to the Alexa Skills Kit, you can say hello", "title": "HelloWorld", "type": "Simple"}, "outputSpeech": {"text": "Welcome to the Alexa Skills Kit, you can say hello", "type": "PlainText"}, "reprompt": {"outputSpeech": {"text": "Welcome to the Alexa Skills Kit, you can say hello", "type": "PlainText"}}, "shouldEndSession": false}, "sessionAttributes": {}, "version": "1.0"}%
```

**Confirming output in the terminal running HelloWorld.py:**
``` bash
$ ASK_VERIFY_REQUESTS=false python samples/helloworld/helloworld.py
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 189-811-296
{
  "request": {
    "locale": "en-US",
    "requestId": "EdwRequestId.45ff9fa9-d4cd-45d8-9d28-81ae39cbee9a",
    "timestamp": "2017-07-11T14:21:47Z",
    "type": "LaunchRequest"
  },
  "session": {
    "application": {
      "applicationId": "amzn1.ask.skill.23926711-b8dd-47ad-a95d-ef1d693d19eb"
    },
    "attributes": {},
    "new": true,
    "sessionId": "SessionId.8474c070-b12c-46b5-be46-241d1aa51dfa",
    "user": {
      "userId": "amzn1.ask.account.AH5QJGCCGTLR6JOF2SFBR6PAPCPWJL52UPSDTS4L7I3WI3537DLJPBBUYSHJCCPGY5YJARNEZZ7CDY4DTK234LMMO5L5KTE3DPPGSLSJS5DYNVDYMAUM3SYZGCK5IGOJSWRILK4T2DTU7PMTPETYTMFKWMOBG22LPVNZA2CYXU5WVQ3KVUQZ2C6NCD3XDJFVBBGMQBD7Z2NXSKI"
    }
  },
  "version": "1.0"
}
{}
{
  "response": {
    "card": {
      "content": "Welcome to the Alexa Skills Kit, you can say hello",
      "title": "HelloWorld",
      "type": "Simple"
    },
    "outputSpeech": {
      "text": "Welcome to the Alexa Skills Kit, you can say hello",
      "type": "PlainText"
    },
    "reprompt": {
      "outputSpeech": {
        "text": "Welcome to the Alexa Skills Kit, you can say hello",
        "type": "PlainText"
      }
    },
    "shouldEndSession": false
  },
  "sessionAttributes": {},
  "version": "1.0"
}
```

**Comment by voutilad** [comment]
@pzzd it seems something might be mangling the requests for some reason. In your skill, try configuring it for debug mode and turn off verification [similar to in the HelloWorld example](https://github.com/johnwheeler/flask-ask/blob/master/samples/helloworld/helloworld.py#L40-L41). 

Try setting `app.config['ASK_VERIFY_REQUESTS'] = False` as well as starting the app with the debug flag like in `app.run(debug=True)`. This should result in turning off the validation and resolving your HTTP_SIGNATURECERTCHAINURL KeyError as well as logging all incoming requests to the console so you can see what is being sent.

Also, for those curious, I dug into the CPython source and CPython [defines a min year of 1 and max year of 9999](https://github.com/python/cpython/blob/314d6fca36a4eaa0541218431d14804fadec6488/Modules/_datetimemodule.c#L40-L41) for those interested.

I did some experimenting and found that the max timestamp value is `253402300800`:
``` python
>>> datetime.utcfromtimestamp(253402300799)
datetime.datetime(9999, 12, 31, 23, 59, 59)
>>> datetime.utcfromtimestamp(253402300800)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: year is out of range
```

And the min value is `-62135596800`:
``` python
>>> datetime.utcfromtimestamp(-62135596800)
datetime.datetime(1, 1, 1, 0, 0)
>>> datetime.utcfromtimestamp(-62135596801)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: year is out of range
```

**Comment by rennomarcus** [comment]
I was having the same problem as @pzzd. 

Using  `app.config['ASK_VERIFY_REQUESTS'] = False` as suggested by @voutilad made the error `ValueError: year is out of range` go away. Thanks.

I'm using Python 3.5.1

**Comment by pzzd** [comment]
I put `app.config['ASK_VERIFY_REQUESTS'] = False` in my skill script and tested the same scenarios as above. This worked out well.

1. curl a json file: KeyError: successful response
2. Text tool in developer.amazon.com: successful response
3. echosim.io: 'try again', no request sent to my laptop

But we don't want to keep `app.config['ASK_VERIFY_REQUESTS'] = False` in our skills scripts to get around the `ValueError: year is out of range` error, correct? What's the next step, @voutilad?

**Comment by LiteWait** [comment]
Like I said I am pretty sure the timestamp Amazon gives you contains milliseconds, you must divide the 1000 or you will get the: **ValueError: year is out of range**

**Comment by voutilad** [comment]
@LiteWait I do believe you're correct about the scale of the numbers, but was hoping to get a sample request before making a change so we could be sure since this format isn't the one documented by Amazon.

I'll implement a relaxed approach if the ValueError occurs the first time. This should resolve the issue.

(Also, looking at this logic again it definitely is a candidate for some refactoring since the verification flags seem a bit redundant.)

**Comment by voutilad** [comment]
Apologies for the cycles here.

@pzzd I just pushed a change to the master branch, but haven't made a new release. This uses @LiteWait's logic for scaling the second from milliseconds to seconds since it seems Python uses seconds represented in floating point under the covers.

Please give that a shot. A `pip install -U git+https://github.com/johnwheeler/flask-ask` should grab the master branch.

**Comment by azevedoph** [comment]
@voutilad Just gave it a shot, as you said, and it solves the problem for me.

**Comment by mtweldon** [comment]
Hmm, I still seem to be having the same problem. I copied over the new files and updated deployment via zappa. still getting errors.

**Comment by ThaWeatherman** [comment]
I installed from the master branch and with the text test interface I still get `OverflowError: timestamp out of range for platform time_t`, but the JSON interface works fine.

**Comment by mtweldon** [comment]
small snippet of the dev tail, I'm still new to this, so posting this in case I missed something easy.. 
`[1499854764319] File "/var/task/flask_ask/core.py", line 591, in _flask_view_func
[1499854764319] ask_payload = self._alexa_request(verify=self.ask_verify_requests)
[1499854764319] File "/var/task/flask_ask/core.py", line 536, in _alexa_request
[1499854764319] timestamp = self._parse_timestamp(raw_timestamp)
[1499854764319] File "/var/task/flask_ask/core.py", line 562, in _parse_timestamp
[1499854764319] return datetime.utcfromtimestamp(timestamp)
[1499854764319] ValueError: year is out of range
[1499854764320] [INFO] 2017-07-12T10:19:24.320Z 93c7778e-66eb-11e7-a993-4b6fef05e99b 72.21.217.137 - - [12/Jul/2017:10:19:24 +0000] "POST / HTTP/1.1" 500 291 "" "Apache-HttpClient/UNAVAILABLE (Java/1.8.0_112)" 0/206.736
[1499857364569] Playing audio playlist
[1499857364570] [2017-07-12 11:02:44,569] ERROR in c:\users\mtwel\appdata\local\temp\pip-build-f1grdt\Flask\flask\app: Exception on / [POST]
[1499857364570] Traceback (most recent call last):
[1499857364570] File "c:\users\mtwel\appdata\local\temp\pip-build-f1grdt\Flask\flask\app.py", line 1982, in wsgi_app
[1499857364570] File "c:\users\mtwel\appdata\local\temp\pip-build-f1grdt\Flask\flask\app.py", line 1614, in full_dispatch_request
[1499857364570] File "c:\users\mtwel\appdata\local\temp\pip-build-f1grdt\Flask\flask\app.py", line 1517, in handle_user_exception
[1499857364570] File "c:\users\mtwel\appdata\local\temp\pip-build-f1grdt\Flask\flask\app.py", line 1612, in full_dispatch_request
[1499857364570] File "c:\users\mtwel\appdata\local\temp\pip-build-f1grdt\Flask\flask\app.py", line 1598, in dispatch_request
[1499857364570] File "/var/task/flask_ask/core.py", line 624, in _flask_view_func
[1499857364570] result = self._map_intent_to_view_func(self.request.intent)()
[1499857364570] File "/var/task/alexa.py", line 859, in alexa_listen_audio_playlist
[1499857364570] playlist = kodi.FindAudioPlaylist(AudioPlaylist)
[1499857364570] File "c:\users\mtwel\appdata\local\temp\pip-build-f1grdt\kodi-voice\kodi_voice\kodi.py", line 422, in FindAudioPlaylist
[1499857364570] AttributeError: 'NoneType' object has no attribute 'encode'
[1499857364570] [INFO] 2017-07-12T11:02:44.570Z a1ab29e6-66f1-11e7-9407-3fd4f113db52 72.21.217.73 - - [12/Jul/2017:11:02:44 +0000] "POST / HTTP/1.1" 500 291 "" "Apache-HttpClient/4.5.x (Java/1.8.0_131)" 0/158.692
[1499857364865] [INFO] 2017-07-12T11:02:44.865Z a1eacab6-66f1-11e7-bafb-3b0e315fa13d 72.21.217.73 - - [12/Jul/2017:11:02:44 +0000] "POST / HTTP/1.1" 200 2 "" "Apache-HttpClient/4.5.x (Java/1.8.0_131)" 0/61.774`

**Comment by ThaWeatherman** [comment]
@mtweldon Do you have that wrapped in the triple backtick, or just a single backtick? It's much more readable when using ```

**Comment by mtweldon** [comment]
Sorry about that, updated

**Comment by voutilad** [comment]
@ThaWeatherman thanks for reporting the `OverflowError`. It seems we're bumping into the system dependent nature of time handling. I'll try spinning up a Windows system with Py27 and also relaxing the `try`/`except` block and see if I can get this working cross platform. 

My initial testing on Win10 with Python 3.6.1 as I write this, I get some very strange errors I'd not expect:

``` bash
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> datetime.utcfromtimestamp(253402300799)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```
I'd say at the least Python should raise the same error across platforms. I may raise this issue with the CPython team.

**Comment by ThaWeatherman** [comment]
@voutilad I guess I should point out that I'm using Python 3.6.1 on Ubuntu 12.04.

**Comment by pzzd** [comment]
@voutilad Here's what happened for me. I tested against my laptop using ngrok, and I didn't set `app.config['ASK_VERIFY_REQUESTS']` to false (so it's true by default, I'm assuming).

1. curl a json file: KeyError: 'HTTP_SIGNATURECERTCHAINURL'. That probably makes sense because of the old session in my json file?
2. Text tool in developer.amazon.com: successful response
3. JSON tool in developer.amazon.com: successful response
4. echosim.io: 'try again', no request sent to my laptop

So that seems to have fixed it for me. I'm happy to keep testing if you need to make more code updates.

**Comment by mtweldon** [comment]
I downgraded to 08.8.. I think? But still getting errors after I used zappa update.

'''
[1499894377312] [DEBUG] 2017-07-12T21:19:37.312Z cf052856-6747-11e7-9eee-01bf05e90b32 Zappa Event: {}
[1499894509135] /var/task/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
[1499894509152] __init__() got an unexpected keyword argument 'path': TypeError
Traceback (most recent call last):
  File "/var/task/handler.py", line 490, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
  handler = cls()
  File "/var/task/handler.py", line 129, in __init__
  self.app_module = importlib.import_module(self.settings.APP_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
  __import__(name)
  File "/var/task/alexa.py", line 39, in <module>
  ask = Ask(app, "/", None, path=TEMPLATE_FILE)
TypeError: __init__() got an unexpected keyword argument 'path'
[1499894543611] [DEBUG] 2017-07-12T21:22:23.599Z 3233a0cd-6748-11e7-8fa9-9902efa96cc1 Zappa Event: {u'body': u'IHsic2Vzc2lvbiI6IAp7InNlc3Npb25JZCI6IlNlc3Npb25JZC5kZTBmNTM5ZS03ZWJjLTRmM2QtOTVhNS0wODg2NWI4MDI3OTIiLCJhcHBsaWNhdGlvbiI6eyJhcHBsaWNhdGlvbklkIjoiYW16bjEuYXNrLnNraWxsLjEwNTRjYWVkLWUyZjgtNDE4Yy04ODUxLTY4ZjM1MWFlYzhhNCJ9LCJhdHRyaWJ1dGVzIjp7fSwidXNlciI6eyJ1c2VySWQiOiJhbXpuMS5hc2suYWNjb3VudC5BSDIzUTJTTUlCRDI1VDVYRFdFSktLNFhJRk1GTVhUWE00V0I1TkJaRFhIRURUUkEzTk1RSU1CUTc2UkJLTjNEMzVFMlA3S1BUNjdaU0g2SFZLRlJQWk41VlFMVVc2SEVRVEpENEFVWEw3VDdLNzdLNU5YUVhTRUFSRkVIUkJLWTdGUEs1N0Y1RFFNNDVHQ1BPQlI1WVdRQUZLNVBPUjY3WkdQWEZGMkZMRU5NNlpHMlNFUURORTVPWlZNNFREVUhSRkRUTFhNQ0hPREVBWUkiLCJhY2Nlc3NUb2tlbiI6bnVsbH0sIm5ldyI6dHJ1ZX0sCiJyZXF1ZXN0IjoKeyJyZXF1ZXN0SWQiOiJFZHdSZXF1ZXN0SWQuZmVmNDMyMjMtZjVlMy00NjA3LTg0YTYtNGZmOWNjOTRmYmNlIiwibG9jYWxlIjoiZW4tVVMiLCJ0eXBlIjoiSW50ZW50UmVxdWVzdCIsInRpbWVzdGFtcCI6MTQ5OTg5NDU0MzQxOCwiaW50ZW50Ijp7Im5hbWUiOiJMaXN0ZW5Ub0F1ZGlvUGxheWxpc3QiLCJzbG90cyI6eyJBdWRpb1BsYXlsaXN0Ijp7Im5hbWUiOiJBdWRpb1BsYXlsaXN0IiwidmFsdWUiOm51bGx9fX19LCJjb250ZXh0Ijp7IlN5c3RlbSI6IHsiYXBwbGljYXRpb24iOiB7ImFwcGxpY2F0aW9uSWQiOiAiYXBwbGljYXRpb25JZCJ9LCAidXNlciI6eyJ1c2VySWQiOiAidXNlcklkIiwicGVybWlzc2lvbnMiOiB7ImNvbnNlbnRUb2tlbiI6ICJjb25zZW50VG9rZW4ifSwiYWNjZXNzVG9rZW4iOiAiYWNjZXNzVG9rZW4ifSwiZGV2aWNlIjogeyAiZGV2aWNlSWQiOiAiZGV2aWNlSWQiLCJzdXBwb3J0ZWRJbnRlcmZhY2VzIjp7fSB9LCJhcGlFbmRwb2ludCI6ICJhcGlFbmRwb2ludCJ9fX0=', u'resource': u'/', u'requestContext': {u'resourceId': u'y5wn1tw6uf', u'apiId': u'2cxyf5qls2', u'resourcePath': u'/', u'httpMethod': u'POST', u'requestId': u'322bffd3-6748-11e7-8c33-ab7848e3a681', u'path': u'/dev', u'accountId': u'058100245157', u'identity': {u'apiKey': u'', u'userArn': None, u'cognitoAuthenticationType': None, u'accessKey': None, u'caller': None, u'userAgent': u'Apache-HttpClient/UNAVAILABLE (Java/1.8.0_112)', u'user': None, u'cognitoIdentityPoolId': None, u'cognitoIdentityId': None, u'cognitoAuthenticationProvider': None, u'sourceIp': u'72.21.217.159', u'accountId': None}, u'stage': u'dev'}, u'queryStringParameters': None, u'httpMethod': u'POST', u'pathParameters': None, u'headers': {u'Content-Type': u'application/json; charset=utf-8', u'Via': u'1.1 247c69d4e44cd66e062b6be2ae5d0b22.cloudfront.net (CloudFront)', u'CloudFront-Is-Desktop-Viewer': u'true', u'CloudFront-Is-SmartTV-Viewer': u'false', u'SignatureCertChainUrl': u'https://s3.amazonaws.com/echo.api/echo-api-cert-4.pem', u'CloudFront-Is-Mobile-Viewer': u'false', u'X-Forwarded-For': u'72.21.217.159, 54.239.145.59', u'CloudFront-Viewer-Country': u'US', u'X-Forwarded-Port': u'443', u'Accept': u'application/json', u'User-Agent': u'Apache-HttpClient/UNAVAILABLE (Java/1.8.0_112)', u'X-Amzn-Trace-Id': u'Root=1-5966930f-3c9a218b20397906048d8168', u'Accept-Charset': u'utf-8', u'Host': u'2cxyf5qls2.execute-api.us-east-1.amazonaws.com', u'X-Forwarded-Proto': u'https', u'X-Amz-Cf-Id': u'krY-rIixj1q3T767dN6GEPd58nlK_cmZF9_Yv9NtN0EDcwP3Eu81_Q==', u'CloudFront-Is-Tablet-Viewer': u'false', u'Signature': u'Gzc5DXQ2U/Nf+bEZUwXp1OT8SL5sfnDF7QvwjYLJsSho0Z3r+QAgVU4LBHWyRMyFU0e7IuBMP2gxEVqDI8FW/ZiycWXVQor0zWiP3YxHCe9aTTiN6J2MhOrihKtSsj0d0l74yHxIN0nrtRUcYzjFxF9/FUOtSx1MjvS7yRieP8errBsU+0WkZ5acJftHRny4lvRiQEY6B3iB7a45IYBrp9UfPEfoajHaAiXqoA2hfNMsuy1HfHPOGzuIdp85PVcFl3/BYT3qP5WxVbEeo3iuBsqpRDmsFa5RtPmGm5NwNrbX74r9qKjIgzV6Bra9MzVXYMRCgVGOSB6DgXJZF3ctkw==', u'CloudFront-Forwarded-Proto': u'https'}, u'stageVariables': None, u'path': u'/', u'isBase64Encoded': True}
[1499894543611] 'NoneType' object is not callable
[1499894611311] [DEBUG] 2017-07-12T21:23:31.292Z 5a85e522-6748-11e7-8d77-7fc608a0f244 Zappa Event: {u'body': u'IHsic2Vzc2lvbiI6IAp7InNlc3Npb25JZCI6IlNlc3Npb25JZC5jMDhkYmI5Yi03MGIzLTRjODQtYWE0Ny1iMjRhYjZjNWUxMzUiLCJhcHBsaWNhdGlvbiI6eyJhcHBsaWNhdGlvbklkIjoiYW16bjEuYXNrLnNraWxsLjEwNTRjYWVkLWUyZjgtNDE4Yy04ODUxLTY4ZjM1MWFlYzhhNCJ9LCJhdHRyaWJ1dGVzIjp7fSwidXNlciI6eyJ1c2VySWQiOiJhbXpuMS5hc2suYWNjb3VudC5BSDIzUTJTTUlCRDI1VDVYRFdFSktLNFhJRk1GTVhUWE00V0I1TkJaRFhIRURUUkEzTk1RSU1CUTc2UkJLTjNEMzVFMlA3S1BUNjdaU0g2SFZLRlJQWk41VlFMVVc2SEVRVEpENEFVWEw3VDdLNzdLNU5YUVhTRUFSRkVIUkJLWTdGUEs1N0Y1RFFNNDVHQ1BPQlI1WVdRQUZLNVBPUjY3WkdQWEZGMkZMRU5NNlpHMlNFUURORTVPWlZNNFREVUhSRkRUTFhNQ0hPREVBWUkiLCJhY2Nlc3NUb2tlbiI6bnVsbH0sIm5ldyI6dHJ1ZX0sCiJyZXF1ZXN0IjoKeyJyZXF1ZXN0SWQiOiJFZHdSZXF1ZXN0SWQuY2Q3NjRmYWItMWViOC00NjllLWEwNWMtZTMxN2Y0YjZjODc2IiwibG9jYWxlIjoiZW4tVVMiLCJ0eXBlIjoiSW50ZW50UmVxdWVzdCIsInRpbWVzdGFtcCI6MTQ5OTg5NDYxMTEwNSwiaW50ZW50Ijp7Im5hbWUiOiJMaXN0ZW5Ub0F1ZGlvUGxheWxpc3RSZWNlbnQiLCJzbG90cyI6e319fSwiY29udGV4dCI6eyJTeXN0ZW0iOiB7ImFwcGxpY2F0aW9uIjogeyJhcHBsaWNhdGlvbklkIjogImFwcGxpY2F0aW9uSWQifSwgInVzZXIiOnsidXNlcklkIjogInVzZXJJZCIsInBlcm1pc3Npb25zIjogeyJjb25zZW50VG9rZW4iOiAiY29uc2VudFRva2VuIn0sImFjY2Vzc1Rva2VuIjogImFjY2Vzc1Rva2VuIn0sImRldmljZSI6IHsgImRldmljZUlkIjogImRldmljZUlkIiwic3VwcG9ydGVkSW50ZXJmYWNlcyI6e30gfSwiYXBpRW5kcG9pbnQiOiAiYXBpRW5kcG9pbnQifX19', u'resource': u'/', u'requestContext': {u'resourceId': u'y5wn1tw6uf', u'apiId': u'2cxyf5qls2', u'resourcePath': u'/', u'httpMethod': u'POST', u'requestId': u'5a7df5a6-6748-11e7-a2ae-07e3fb59690c', u'path': u'/dev', u'accountId': u'058100245157', u'identity': {u'apiKey': u'', u'userArn': None, u'cognitoAuthenticationType': None, u'accessKey': None, u'caller': None, u'userAgent': u'Apache-HttpClient/UNAVAILABLE (Java/1.8.0_112)', u'user': None, u'cognitoIdentityPoolId': None, u'cognitoIdentityId': None, u'cognitoAuthenticationProvider': None, u'sourceIp': u'72.21.217.171', u'accountId': None}, u'stage': u'dev'}, u'queryStringParameters': None, u'httpMethod': u'POST', u'pathParameters': None, u'headers': {u'Content-Type': u'application/json; charset=utf-8', u'Via': u'1.1 6419ba8f3bd94b651d416054d9416f1e.cloudfront.net (CloudFront)', u'CloudFront-Is-Desktop-Viewer': u'true', u'CloudFront-Is-SmartTV-Viewer': u'false', u'SignatureCertChainUrl': u'https://s3.amazonaws.com/echo.api/echo-api-cert-4.pem', u'CloudFront-Is-Mobile-Viewer': u'false', u'X-Forwarded-For': u'72.21.217.171, 54.239.145.12', u'CloudFront-Viewer-Country': u'US', u'X-Forwarded-Port': u'443', u'Accept': u'application/json', u'User-Agent': u'Apache-HttpClient/UNAVAILABLE (Java/1.8.0_112)', u'X-Amzn-Trace-Id': u'Root=1-59669353-4f912056004fc50a262a4104', u'Accept-Charset': u'utf-8', u'Host': u'2cxyf5qls2.execute-api.us-east-1.amazonaws.com', u'X-Forwarded-Proto': u'https', u'X-Amz-Cf-Id': u'hsX3ECJh8-eEBsBLl_XraylFFXKJrbjYydi3783Fe8WhAYDYa5YdTw==', u'CloudFront-Is-Tablet-Viewer': u'false', u'Signature': u'atQ7z+5o3xdewqaz35RfuoKJQ8pbpdkA/rMztLXe4yAskfsIdDonAMeoOfghvrFsa9TL+P8wAbwpaUm1sdRoBKy5dE2deTLssRQWMHRuZ9EcjifAkW8LRVyI9q6w3hiNDIcYq0nOsvicAa5w6qnBsLnzVokHtMgNyocsNo9Q0aYVvRvby624gjYUUfNcgO150+h3mGgCTgE8UdCy1qeFmzGeyQTEtHKWxGfd65UOxSHmttDoPLmHBfk/A6enypB9U9eCtgVm+5J5y2lJnNyPG4qSK6UCiIvO5h/5Kdf8TGmXq3OCwmqrIpRZ4DoD9OxDxjRTkgleCz7kt4QjVAfhCw==', u'CloudFront-Forwarded-Proto': u'https'}, u'stageVariables': None, u'path': u'/', u'isBase64Encoded': True}
[1499894611311] 'NoneType' object is not callable
[1499894616640] [DEBUG] 2017-07-12T21:23:36.640Z 5db4b6b0-6748-11e7-80bc-19e1a25419b5 Zappa Event: {u'account': u'058100245157', u'region': u'us-east-1', u'detail': {}, u'detail-type': u'Scheduled Event', u'source': u'aws.events', u'version': u'0', u'time': u'2017-07-12T21:23:15Z', u'id': u'32a1354f-dbab-491f-87fe-2ca41abb6710', u'resources': [u'arn:aws:events:us-east-1:058100245157:rule/kodi-alexa-mast-dev-zappa-keep-warm-handler.keep_warm_callback']}
[1499894616641] [DEBUG] 2017-07-12T21:23:36.640Z 5db4b6b0-6748-11e7-80bc-19e1a25419b5 Zappa Event: {}
'''

**Comment by voutilad** [comment]
@pzzd That `KeyError` is to be expected if testing locally and not disabling verification. It's nothing to do with the session and it's because the request you're making with CURL isn't authenticating itself using Amazon's certificate (which makes sense since you're not Amazon).

I'll make a new release after I can run some more tests across platforms just to be safe.

**Comment by tguidon** [comment]
@voutilad I'm still seeing errors on my end. I have tried version 0.9.5 and also `pip install -U git+https://github.com/johnwheeler/flask-ask`.

In my .py file I have `app.config['ASK_VERIFY_REQUESTS'] = False` and `app.run(debug=True)` set.

My problem occurs when using ngrok and testing with the Amazon text tool. Amazon returns "The remote endpoint could not be called, or the response it returned was invalid." and nothing gets logged by Flask-Ask.

**Comment by voutilad** [comment]
@tguidon if nothing is logged by Flask-Ask chances are it's an issue with your ngrok setup. Can you try testing locally with `curl` or a similar tool per my steps in [one of the previous comments](https://github.com/johnwheeler/flask-ask/issues/152#issuecomment-314478181 )?

**Comment by tguidon** [comment]
@voutilad yep you can ignore all that 🙃. I had the wrong SSL settings in the Amazon developer panel.

Using 0.9.5 and setting `app.config['ASK_VERIFY_REQUESTS'] = False` allows me to test with the Amazon Text simulator.

Thanks!

**Comment by voutilad** [comment]
v0.9.6 contains the latest changes in master for better handling of timestamps.
